let money = 80000;
let income = '20000';
let addExpenses = 'Интернет, такси, комуналка';
let deposit = false;
let mission = 1000000;
let period = 6;
console.log(typeof money);
console.log(typeof income);
console.log(typeof deposit);
console.log(addExpenses.length);
console.log('Период равен ' + period + ' месяцев');
console.log('Цель заработать ' + mission + ' рублей');
console.log(addExpenses.toLowerCase().split(', '));
let budgetDay = money / 30;
console.log('budgetDay: ', budgetDay);
